// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqC3FkCKsVaXMdPVlOgPHjzZyKjJdnZY',
    appId: '1:413613593282:web:08aab06d8d9a9687f5615b',
    messagingSenderId: '413613593282',
    projectId: 'isplit-affb5',
    authDomain: 'isplit-affb5.firebaseapp.com',
    storageBucket: 'isplit-affb5.firebasestorage.app',
    measurementId: 'G-YLJTEFDJB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAkoYUCtcxmK3bJPZ5Zc2WKg8dZ6gdiU',
    appId: '1:413613593282:android:8cfbec252f16ec2df5615b',
    messagingSenderId: '413613593282',
    projectId: 'isplit-affb5',
    storageBucket: 'isplit-affb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjbp7hzVsk50xrxPKa9suyAovKqkdQU4w',
    appId: '1:413613593282:ios:8ead3a9cc6510dbff5615b',
    messagingSenderId: '413613593282',
    projectId: 'isplit-affb5',
    storageBucket: 'isplit-affb5.firebasestorage.app',
    iosBundleId: 'com.example.isplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjbp7hzVsk50xrxPKa9suyAovKqkdQU4w',
    appId: '1:413613593282:ios:8ead3a9cc6510dbff5615b',
    messagingSenderId: '413613593282',
    projectId: 'isplit-affb5',
    storageBucket: 'isplit-affb5.firebasestorage.app',
    iosBundleId: 'com.example.isplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjqC3FkCKsVaXMdPVlOgPHjzZyKjJdnZY',
    appId: '1:413613593282:web:9adea44a84bcb085f5615b',
    messagingSenderId: '413613593282',
    projectId: 'isplit-affb5',
    authDomain: 'isplit-affb5.firebaseapp.com',
    storageBucket: 'isplit-affb5.firebasestorage.app',
    measurementId: 'G-XF8JSHVTWE',
  );
}
