import 'package:animated_splash_screen/animated_splash_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'features/onboarding/presentation/sliding_pages/onboarding_screen.dart';
import 'firebase_options.dart'; // Generated by Firebase CLI
import 'core/theming/theme.dart';
import 'core/theming/text_styles.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      home: AnimatedSplashScreen(
        splash: SizedBox.expand(
          child: Image.asset(
            'assets/images/iSplit_animation.gif',
            fit: BoxFit.fill,
          ),
        ),
        nextScreen: const OnBoardingScreen(),
        duration: 3100,
        splashIconSize: double.infinity,
        splashTransition: SplashTransition.fadeTransition,
        animationDuration: const Duration(milliseconds: 800),
      ),
    );
  }
}